website/models.py
# Database creation 
from . import db, login_manager
from flask_login import UserMixin

# finding the user by the user id
@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

# stores the user information into a table
class User(db.Model, UserMixin):
  id = db.Column(db.Integer, primary_key=True)
  first_name = db.Column(db.String(50), nullable=False)
  last_name = db.Column(db.String(50), nullable=False)
  username = db.Column(db.String(20), unique=True, nullable=False)
  email = db.Column(db.String(150), unique=True, nullable=False)
  password = db.Column(db.String(60), nullable=False)
  
  # magic method - this sets how the User object will display in the command line
  def __repr__(self):
    return f"User('{self.username}','{self.email}')"

website/forms.py
# Forms for Registration and Login

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from website.models import User

# Registration Form Class
class RegistrationForm(FlaskForm):
  first_name = StringField("First Name", validators=[DataRequired()])
  last_name = StringField("Last Name", validators=[DataRequired()])
  email = StringField('Email Address', validators=[DataRequired(), Email()])
  username = StringField('Username', validators=[DataRequired(), Length(min=5, max=20)])
  password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=20)])
  confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=8, max=20), EqualTo('password', message='Passwords must match')])
  submit = SubmitField("Create Account")
  
  # checks if the username exists in the database
  def validate_username(self, username):
    user = User.query.filter_by(username=username.data).first()
    if user:
      raise ValidationError('Username is taken. Please choose a different username!')

  # checks if the email address exists in the database
  def validate_email(self, email):
    user = User.query.filter_by(email=email.data).first()
    if user:
      raise ValidationError('Email address exists. Please use a different one!')

# Login Form Class
class LoginForm(FlaskForm):
  email = StringField('Email Address', validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  remember = BooleanField('Remember Me')
  submit = SubmitField("Login")

website/__init__.py
# Setting up Flask Application
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_session import Session

# creating an instance of the SQLAlchemy class
db = SQLAlchemy()
db_name = "user_database.db"
# creating an instance of the Bcrypt class
bcrypt = Bcrypt()
# creating an instance of the LoginManager class
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'info'

def create_app():
  # represents the name of the file
  app = Flask(__name__) 
  # secures the cookies and session data related to the website
  app.config['SECRET_KEY'] = '1533e2ab57a4a84099e9ba68935b9d44'
  app.config["SESSION_TYPE"] = "filesystem"
  # links the database to app
  app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{db_name}'
  # initialising the datbase
  db.init_app(app)
  # initialising the bycrpt
  bcrypt.init_app(app)
  # initialising the login_manager
  login_manager.init_app(app)
  Session(app)
  
  # registering our Blueprint
  from .views import views
  from .auth import auth
  
  # registering with the Flask app
  app.register_blueprint(views, url_prefix='/')
  app.register_blueprint(auth, url_prefix='/')
  
  # db class
  from website.models import User

  create_database(app)

  return app

# if database does not exist, create database
def create_database(app):
  if not path.exists('website/' + db_name):
      db.create_all(app=app)
      print('Database created')

website/auth.py
# authorisation routes
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import login_user, logout_user, current_user
from website import db, bcrypt
from website.models import User
from website.forms import RegistrationForm, LoginForm

# defining this file is a Blueprint of our application, it has a group of URL's

auth = Blueprint('auth', __name__)

# login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
  # checks if the user is logged in, if it is direct to the homepage
  if current_user.is_authenticated:
    return redirect(url_for('views.home'))
  login_form = LoginForm()
  if login_form.validate_on_submit():
    # checks to see if the user is in the database
    user = User.query.filter_by(email=login_form.email.data).first()
    if user:
      # checks password entered matches the stored hashed password 
      if bcrypt.check_password_hash(user.password, login_form.password.data):
        login_user(user, remember=login_form.remember.data)
        return redirect(url_for('views.home'))
      else:
        flash('Incorrect password. Please try again!', 'danger')
    else: 
      flash('User account does not exist. Please try again!', 'danger')
  return render_template('login.html', title='Login', form=login_form)

# registration route
@auth.route('/register', methods=['GET', 'POST'])
def register():
  # checks if the user is logged in, if it is direct the user to the homepage
  if current_user.is_authenticated:
    return redirect(url_for('views.home'))
  # creates an instance for the RegistrationForm class
  register_form = RegistrationForm()
  if register_form.validate_on_submit():
    # hashing the password to a string
    hashed_password = bcrypt.generate_password_hash(register_form.password.data).decode('utf-8')
    
    # creating new instance of user
    user = User(first_name=register_form.first_name.data, last_name=register_form.last_name.data, username=register_form.username.data, email=register_form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    
    # if successful display message and redirect user to login page
    flash(f'Your account has been created. You can now login!', 'success')
    return redirect(url_for('auth.login'))
  return render_template("sign_up.html", title='Register', form=register_form)

# logout route
@auth.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('views.home'))

website/views.py
# stores the URL end points for the front-end websites
# store standard routes - where the user can go to
from flask import Blueprint, render_template, redirect, request
from flask import session
from .api_helpers import get_user_location, get_user_weather, get_spotify_user_auth, call_spotify, get_user_playlists, get_spotify_token

# defining Blueprint
views = Blueprint('views', __name__)

# home page
@views.route("/", methods=['GET', 'POST'])
@views.route("/home", methods=['GET', 'POST'])
def home():
	location = get_user_location()
	weather = get_user_weather(location)
	playlist = call_spotify(weather)
	return render_template('index.html', playlist=playlist)

# about page
@views.route("/about")
def about():
	return render_template('about.html', title = 'About')

# playlist page
@views.route("/playlist")
def playlist_page():
  location = get_user_location()
  weather = get_user_weather(location)
  playlist = call_spotify(weather)
  return render_template('playlist.html', title = 'Playlist', playlist=playlist)

# Starts the Spotify authorisation process
@views.route("/spotify_login")
def spotify_login():
	username = "Brezita"
	auth_url = get_spotify_user_auth(session, username)

	if auth_url == 1:
		return redirect("/playlist")
	else:
		return redirect(auth_url)

# Completes the Spotify authorisation process and redirects user back to home
@views.route("/callback")
def spotify_callback():
  code = request.args.get("code")
  get_spotify_token(session, code)
  return redirect("/playlist")

# Not used - will eventually allow user playlists to be passed to template
@views.route("/user_playlists")
def user_playlists():
	return get_user_playlists(session)

website/templates/about.html
<!-- takes the layout template -->
{% extends "layout.html" %}

<!-- Page Heading -->
{% block heading1 %}
  <h1>About</h1>
{% endblock heading1%}

<!-- main section for the page -->
{% block container_box %}
<div class="container-wrapper">
  <div class="row">
    <div class="col-sm border-box">
      <h3 class="about-app-heading">Cloudtunes</h3>
      <p class="about-text">Cloudtunes was born in 2021, with the idea of bringing some extra joy to your life, by selecting songs based on your current weather.</p>
      <p class="about-text">Just because it's raining outside, doesn't mean you can't listen to some upbeat tunes! 🌦 🌩 🎧</p>
      <br />
      <p class="about-text">Have a little read about our Cloudtunes co-creators!</p>
    </div>
    <div class="col-sm border-box">
      <h3 class="about-heading">Jules</h3>
      <p class="about-text">When I'm not pulling my hair out, because I added one too many identations to my Python code...I'm a self-professed foodie and skincare lover. 👩🏻‍🍳 🧖🏻‍♀️</p>
      <p class="about-text">Cute little coffee shops, delicious pastries and cakes are my calling! ☕️ 🥐 🍰</p>
      <p class="about-text"><b>Current favourite song:</b> <a href="https://open.spotify.com/track/0LThjFY2iTtNdd4wviwVV2?si=ac99a18da3354f6e" class="sign-link" target="_blank">BTS - Permission To Dance</a></p>
    </div>
    <div class="col-sm border-box">
      <h3 class="about-heading">Heather</h3>
      <p class="about-text">For a technology lover, I sure own a lot of pens and notebooks. 🖋️ 📓</p>
      <p class="about-text">If I'm not streaming music, I'm probably making music. Other hobbies include: playing videogames, parenting my houseplants, embroidering and losing at mini golf! 🎮 🪴 ⛳️</p>
      <p class="about-text"><b>Current favourite song:</b> <a href="https://open.spotify.com/playlist/2DsYfCPWDxZtFzHRj9mO4h?si=muua3cWFRvK6HJmGpuXUpA" class="sign-link" target="_blank">Most Sea Shanties</a></p>

    </div>
  </div>
<div class="spacing"></div>
  <div class="row">
    <div class="col-sm border-box">
      <h3 class="about-heading">Alex</h3>
      <p class="about-text">Trying to put the fun back in functional programming. ✨ Puts the OOPs back in OOP.</p>
      <p class="about-text">Never afraid to be the only person laughing! ✌️ Self-confessed cactus killer and spice lover. 🌵 🌶 🔥</p>
      <p class="about-text"><b>Current favourite song:</b> <a href="https://open.spotify.com/track/1zVMJGPMWKmD4cjTTyf68y?si=f18f63513cb941db" class="sign-link" target="_blank">Rasputin - Club Mix (Boney M, G.Mart)</a></p>
    </div>
    <div class="col-sm border-box">
      <h3 class="about-heading">Johanna</h3>
      <p class="about-text">Currently reading "Once Upon An Algorithm" - fairy tales + computing. Recursion told through Back to the future...almost got it! 📚 </p>
      <or class="about-text">When I'm not practising my flamenco moves 💃, I'm probably at my piano 🎹 or dragging a gang of peeps up a mountain. ⛰️ </p>
      <p class="about-text"><b>Current favourite song:</b> <a href="https://open.spotify.com/track/5CKHhg31HcYYhwUeeGqvhq?si=c761e26451094710 " class="sign-link" target="_blank">Nina Simona - I Wish I Knew How It Would Feel To Be Free</a></p>
    </div>
    <div class="col-sm border-box">
      <h3 class="about-heading">Kara</h3>
      <p class="about-text">I'm a problem solver by nature and coding gives me all the challenge I need.</p>
      <p class="about-text">I enjoy learning and teaching others and when I have some free time, I love to visit animal sanctuaries with my 2 children. I am also now a mum to 6 fluffy chicks. 👩‍🏫  💭 🐣 </p>
      <p class="about-text"><b>Current favourite song:</b> <a href="https://open.spotify.com/track/7qDuDGkw8JPYYmoL87W54T?si=6bf9e1fe805145bb" class="sign-link" target="_blank">Mr FijiWiji & Matt Van - Iris</a></p>
    </div>
  </div>
</div>


{% endblock container_box %}

website/templates/index.html
<!-- takes the layout template -->
{% extends "layout.html" %}

<!-- Page Heading -->
{% block heading1 %}
  <h1>Welcome to Cloudtunes</h1>
{% endblock heading1%}

<!-- main section for the page -->
{% block container_box %}
<!-- cloud animations -->
<div class="background-wrap">
  <div class="cloud-1">
    <div class="cloud"></div>
  </div>
  <div class="spacing"></div>
  <div class="cloud-2">
    <div class="cloud"></div>
  </div>
  <div class="spacing"></div>
  <div class="cloud-3">
    <div class="cloud"></div>
  </div>
  <div class="spacing"></div>
  <div class="cloud-4">
    <div class="cloud"></div>
  </div>
  <div class="spacing"></div>
  <div class="cloud-5">
    <div class="cloud"></div>
  </div>
</div>
<div class="container-wrapper">
  <div class="row">
    <div class="col">
      <h2>Current Location:</h2> 
      <br/>
      <p class="yellow-text">{{ playlist.PlaylistLocationData.location}}, {{ playlist.PlaylistLocationData.country}}</p>
      <br />
      <h2>Current Weather:</h2> 
      <br/>
      <p class="yellow-text">{{ playlist.PlaylistLocationData.weather }}</p>
    </div>
  </div>
  <div class="row pt-5">
    <div class="col">
      <p>Bored of listening to the same songs over and over again?</p>
      <p>Why don't you let us curate a playlist for you today!</p>
      <p class="yellow-text">Click on the below button and find out what music you can be listening to today!</p>
    </div>
  </div>
  <div class="row pt-4">
    <div class="col">
      {% if current_user.is_authenticated %}
        <a href="{{url_for('views.playlist_page')}}"><button class="btn btn-lg btn-info">Go to playlist</button></a>
      {% else %}
        <a href="{{url_for('views.spotify_login')}}"><button class="btn btn-lg btn-info">Login to Spotify</button></a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock container_box %}

website/templates/layout.html
<!-- base layout template -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% if title %}
    <title>Cloudtunes - {{ title }}</title>
  {% else %}
    <title>Cloudtunes</title>
  {% endif %}

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Website CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='/main.css') }}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
 <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&display=swap" rel="stylesheet">

 <!--Misc CSS-->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand mr-4" href="/"><img src="{{ url_for('static', filename='/images/cloud_logo.jpg') }}" alt="cloud logo" width="30" height="30" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link mr-4" href="{{url_for('views.home')}}">HOME</a>
            <a class="nav-item nav-link mr-4" href="{{url_for('views.about')}}">ABOUT</a>
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{url_for('views.playlist_page')}}">PLAYLIST</a>
            {% endif %}
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <!-- checks if the user is logged in, if they are will display logout button  -->
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link mr-4" href="{{url_for('auth.logout')}}">LOGOUT</a>
            {% else %}
              <a class="nav-item nav-link mr-4" href="{{url_for('auth.login')}}">LOGIN</a>
              <a class="nav-item nav-link" href="{{url_for('auth.register')}}">REGISTER</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row heading-box">
    <!-- use this to add in a page heading -->
      {% block heading1 %}
      {% endblock heading1 %}
    </div>
    <!-- section for the page -->
    <div class="container-box">
      {% block container_box %}
      {% endblock container_box %}
    </div>
  </main>
  <!-- footer -->
  <footer class="footer fixed-bottom">
    <div class="container-fluid">
      <div class="row footer-box">
        <div class="col">
          <p class="footer-p">CFG Project</p>
        </div>
        <div class="col">
          <p class="footer-p">&copy; Cloudtunes <script>document.write(new Date().getFullYear())</script></p>
        </div>
      
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

website/templates/login.html
{% extends "layout.html" %}
{% block heading1 %}
  <h1>Login</h1>
{% endblock heading1 %}
{% block container_box %}
<div class="row content-box">
   <!-- this section handles success/error messages -->
  <div class="content-message-box">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
  <!-- login form section -->
  <div class="content-form-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <div class="form-group">
          {{ form.email.label(class="form-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control is-invalid", placeholder="jane.doe@doe.com") }}  
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control", placeholder="jane.doe@doe.com") }}  
          {% endif%}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control is-invalid", placeholder="Enter your password") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}   
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
          {% else %}
            {{ form.password(class="form-control", placeholder='Enter your password') }}
          {% endif %}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input", type="checkbox") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group mt-4 mb-4">
        {{ form.submit(class="btn btn-outline-info btn-lg") }}
      </div>
      <small class="text-muted m1-2">
        <a class="ml-2 sign-link" href="#"> Forgot Password?
        </a>
      </small>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
          Need an account? <a class="ml-2 sign-link" href="{{ url_for('auth.register') }}">Sign Up Now</a>
      </small>
    </div>
  </div>
</div>
{% endblock container_box %}

website/templates/playlist.html
<!-- takes the layout template -->
{% extends "layout.html" %}

<!-- Page Heading -->
{% block heading1 %}
  <h1>Your Curated Playlist</h1>
{% endblock heading1%}

<!-- main section for the page -->
{% block container_box %}
<!-- cloud animations -->
<div class="background-wrap">
  <div class="cloud-1">
    <div class="cloud"></div>
  </div>
  <div class="cloud-2">
    <div class="cloud"></div>
  </div>
  <div class="cloud-3">
    <div class="cloud"></div>
  </div>
  <div class="cloud-4">
    <div class="cloud"></div>
  </div>
  <div class="cloud-5">
    <div class="cloud"></div>
  </div>
  <div class="cloud-6">
    <div class="cloud"></div>
  </div>
</div>
<div class="container-wrapper">
  <div class="row">
    <!-- current weather and location section -->
    <div class="col-sm">
      <h2>Current Location:</h2> 
      <br/>
      <p class="yellow-text">{{ playlist.PlaylistLocationData.location}}, {{ playlist.PlaylistLocationData.country}}</p>
      <br />
      <h2>Current Weather:</h2> 
      <br/>
      <p class="yellow-text">{{ playlist.PlaylistLocationData.weather }}</p>
    </div>
    <!-- diplays the playlists based on current weather -->
    <div class="col-sm">
      <h2>Your Playlist:</h2> 
      <br/>
      {% for item in playlist.tracks %}
        <a href={{ item.url }} class="song-link" target="_blank">{{ item.title }}</a>
        <br/>
      {% endfor %}
    </div>
    <!-- spotify player -->
    <div class="col-sm">
      <iframe src="https://open.spotify.com/embed/track/{{playlist.tracks[0].spotifyid}}" width="280" height="380" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
  </div>
</div>
{% endblock container_box %}

website/templates/sign_up.html
{% extends "layout.html" %}
{% block heading1 %}
  <h1>Create Account</h1>
{% endblock heading1 %}
{% block container_box %}
<div class="row content-box">
  <!-- this section handles success/error messages -->
  <div class="content-message-box">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith%}
  </div>
  <!-- registration form section -->
  <div class="content-form-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
        <div class="row mt-4">
          <div class="col">
            {{ form.first_name.label(class="form-label") }}
            {% if form.first_name.errors %}
              {{ form.first_name(class="form-control is-invalid", placeholder="Jane") }}
              <div class="invalid-feedback">
                {% for error in form.first_name.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.first_name(class="form-control", placeholder="Jane") }}
            {% endif %}
          </div>
          <div class="col">
            {{ form.last_name.label(class="form-label") }}
            {% if form.last_name.errors %}
              {{ form.last_name(class="form-control is-invalid", placeholder="Doe") }}
              <div class="invalid-feedback">
                {% for error in form.last_name.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.last_name(class="form-control", placeholder="Doe") }}
            {% endif %}
          </div>
        </div>
        <div class="row mt-4">
          <div class="col">
            {{ form.email.label(class="form-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control is-invalid", placeholder="jane.doe@doe.com") }}  
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control", placeholder="jane.doe@doe.com") }}  
            {% endif %}
          </div>
          <div class="col">
            {{ form.username.label(class="form-label") }}
            {% if form.username.errors %}
              {{ form.username(class="form-control is-invalid", placeholder="username") }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}   
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
            {% else %}
              {{ form.username(class="form-control", placeholder='username') }}
            {% endif %}
          </div>
        </div>
        <div class="row mt-4">
          <div class="col">
            {{ form.password.label(class="form-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control is-invalid", placeholder="Enter a password") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}   
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
            {% else %}
              {{ form.password(class="form-control", placeholder='Enter a password') }}
            {% endif %}
          </div>
          <div class="col">
            {{ form.confirm_password.label(class="form-label") }}
            {% if form.confirm_password.errors %}
              {{ form.confirm_password(class="form-control is-invalid", placeholder="Confirm password") }}
                <div class="invalid-feedback">
                  {% for error in form.confirm_password.errors %}   
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
            {% else %}
              {{ form.confirm_password(class="form-control", placeholder='Confirm password') }}
            {% endif %}
          </div>
        </div>
      <div class="form-group m-5">
      {{ form.submit(class="btn btn-outline-info btn-lg") }}
      </div>
    </form>
    <div class="border-top mt-4 pt-3">
      <small class="text-muted">
        Already have an account? <a class="ml-2 sign-link" href="{{ url_for('auth.login') }}"> Sign In</a>
      </small>
    </div>
  </div>
</div>
{% endblock container_box %}